// @ts-ignore
import gearIcon from "../../assets/icons/gear.svg";
// @ts-ignore
import dataCollectionIcon from "../../assets/icons/data-collection.svg";
import { useState } from "react";
import { useAppStore } from "../../store/store";
import Switch from "../Switch";

const Settings = () => {
  const { setSetting, settings } = useAppStore();
  const [isCheckingData, setIsCheckingData] = useState(settings.collectData);
  const onChange = (checked: boolean) => {
    setIsCheckingData(checked);
    setSetting("collectData", checked);
  };

  const getVersion = () => {
    // @ts-ignore
    return window.electronAPI.getAppVersion();
  }
  const getVersionHash = () => {
    // @ts-ignore
    return window.electronAPI.getAppVersionHash();
  }
  return (
    <div className="h-full px-[145px] pt-[126px]">
      <span className="flex items-center gap-[10px]">
        <img src={gearIcon} className="w-6 h-6" />
        <h1 className="text-surface-main text-[32px]">Settings</h1>
      </span>

      <div className="flex justify-between items-start mt-[40px]">
        <div className="flex justify-start items-start flex-col gap-4">
          <span className="flex-center gap-2">
            <img
              src={dataCollectionIcon}
              alt="data collection"
              className="w-[14px] h-[14px]"
            />
            <div className="flex flex-row gap-2 justify-center items-center">
              <p>Data Collection</p>
            </div>
          </span>

          <span
          className={`text-surface-main text-[14px] transition-opacity duration-300`}
          >
            We're not ClosedAI. Our software, designed for downloading and
            running local models, does not collect any usage data or personal
            information. The only data we gather is anonymous feedback about
            which features you find most valuable. This helps us make informed
            decisions about future developments and improvements. We do not
            track, store, or share any information that could identify you
            personally, nor do we save any data that corresponds to
            prompts/completions generated by models you run. Your models and
            data remain entirely on your local device. This toggle turns off our
            ability to see what features you like the best.
            <br/> <br/>
            We get it if you
            want to turn it off — please send us feedback another way:
            <span 
            className="text-surface-main cursor-pointer"
            onClick={() =>  {
              // @ts-ignore
              window.electronShell.openExternal("https://discord.gg/itsalltruffles");
            }}
            > discord.gg/itsalltruffles</span>
          </span> 
        </div>
        <Switch
          value={isCheckingData}
          onChange={onChange}
          className={`${isCheckingData ? "switch-enabled" : ""}`}
        />
      </div>

      <div className="absolute bottom-0 right-3 text-surface-500 text-xs">
        v{getVersion()} {getVersionHash()}
      </div>
    </div>
  );
};

export default Settings;
