import { TModel } from "../types/schemas";

export const MODEL_LIST: TModel[] = [
    {
      id: "00000000-0000-0000-0000-000000000000",
      instance: 0,
      url: "https://huggingface.co/togethercomputer/RedPajama-INCITE-Instruct-3B-v1",
      status: "NOT_DOWNLOADED",
      backgroundImage: process.env.NODE_ENV === "development" ? "/assets/images/llama1.png" : "../../renderer/main_window/assets/images/llama1.png",
      author: "Meta",
      name: "Llama 7B",
      params: 0,
    },
    {
      id: "00000000-0000-0000-0000-000000000001",
      instance: 1,
      url: "https://huggingface.co/abacusai/Smaug-Llama-3-70B-Instruct",
      status: "NOT_DOWNLOADED",
      backgroundImage: process.env.NODE_ENV === "development" ? "/assets/images/llama1.png" : "../../renderer/main_window/assets/images/llama1.png",
      author: "Abacus AI",
      name: "Smaug-Llama-3-70B-Instruct",
      params: 0,
    },
    {
      id: "00000000-0000-0000-0000-000000000002",
      instance: 2,
      url: "https://huggingface.co/google/paligemma-3b-pt-224",
      status: "STOPPED",
      backgroundImage: process.env.NODE_ENV === "development" ? "/assets/images/llama1.png" : "../../renderer/main_window/assets/images/llama1.png",
      author: "google",
      name: "paligemma-3b-pt-224",
      params: 0,
    },
    {
      id: "00000000-0000-0000-0000-000000000003",
      instance: 3,
      url: "https://huggingface.co/CohereForAI/aya-23-8B",
      status: "STOPPED",
      backgroundImage: process.env.NODE_ENV === "development" ? "/assets/images/llama1.png" : "../../renderer/main_window/assets/images/llama1.png",
      author: "Cohere",
      name: "aya-23-8B",
      params: 0,
    },
    {
      id: "00000000-0000-0000-0000-000000000004",
      instance: 4,
      url: "https://huggingface.co/openai-community/gpt2",
      status: "STOPPED",
      backgroundImage: process.env.NODE_ENV === "development" ? "/assets/images/llama1.png" : "../../renderer/main_window/assets/images/llama1.png",
      author: "OpenAI",
      name: "gpt2",
      params: 0,
    },
];