name: Frontend tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Install Bun
      run: npm install -g bun

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun test

    - name: Slack Notification on Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,action,eventName,ref,workflow

    - name: Slack Notification on Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,action,eventName,ref,workflow
        custom_payload: |
          {
            "attachments": [{
              "color": "good",
              "text": "Successfully completed CI pipeline for ${{ github.repository }} on commit ${{ github.sha }} by ${{ github.actor }}."
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}