name: Integration tests

on: 
  pull_request:
  workflow_dispatch:

jobs:
  integration_tests:
    strategy:
      matrix:
        os: [
          ubuntu-latest, # no GPU
          ubuntu-x64-1x-T4, # 1x T4
          ubuntu-x64-2x-T4, # 2x T4
          macos-13, # no GPU
          macos-latest, # M1
          self-hosted, # self-hosted
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - run: uname -a

