name: Python tests

on: [pull_request]

jobs:
  python_tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "sqlite:///${{ github.workspace }}/truffle.test.db"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          cd python
          python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly mlc-llm-nightly
          pip install -r requirements.txt

      - name: Run database migrations
        run: |
          cd python
          python migrations.py

      - name: Run tests
        run: |
          cd python
          PYTHONPATH="." pytest -s --maxfail=1 -v tests/
