name: Python tests

on: [pull_request]

jobs:
  python_tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "${{ github.workspace }}/truffle.test.db"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        env:
          PIP_EXTRA_INDEX_URL: "https://mlc.ai/wheels"
        run: |
          cd python
          pip install -r requirements.txt

      - name: Create test database
        run: |
          cd python
          prisma db push --schema ./prisma/schema.prisma

      - name: Run tests
        run: |
          cd python
          PYTHONPATH="." pytest -s -v tests/
