name: Python integration ests

on: 
  pull_request:
  workflow_dispatch:

jobs:
  python_integration_tests:
    strategy:
      matrix:
        os: [ubuntu-x64-1x-T4, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - run: nvidia-smi
        if: runner.os == 'Linux'