name: Release server executable

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    env:
      SERVER_FILENAME: server-${{ github.sha }}-${{ matrix.os }}.tar.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install MLC and TVM
        if: matrix.os == 'macos-latest'
        run: |
          pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly

      - name: Install rest of the dependencies
        run: |
          pip install -r python/requirements.txt

      - name: Build server executable
        run: |
          cd python
          pyinstaller server.spec --clean --noconfirm --log-level=DEBUG

      - name: Archive server executable
        run: |
          tar -czvf ${{ env.SERVER_FILENAME }} -C python/dist server
        working-directory: python

      - name: List files
        run: ls -l

      - name: Upload server executable
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ${{ env.SERVER_FILENAME }}
          path: |
            *.tar.gz