name: Release server executable

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-cuda12.1-1xt4-x86_64]
        include:
          - os: macos-latest
            filename: darwin-metal-arm64.tar.gz
          - os: ubuntu-cuda12.1-1xt4-x86_64
            filename: ubuntu-cuda-x86_64.tar.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install MLC
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly
          elif [ "${{ matrix.os }}" == "ubuntu-cuda12.1-1xt4-x86_64" ]; then
            pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu121 mlc-ai-nightly-cu121
          fi

      - name: Install rest of the dependencies
        run: |
          pip install -r python/requirements.txt

      - name: Build server executable
        run: |
          cd python
          pyinstaller server.spec --clean --noconfirm --log-level=DEBUG

      - name: Archive server executable
        run: |
          echo "Copying alembic migrations"
          cp -r python/alembic python/dist/server/alembic
          echo ${{ github.sha }} > python/dist/server/latest.txt
          cd python/dist 
          tar -czvhf ${{ matrix.filename }} server

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp python/dist/${{ matrix.filename }} s3://truffle-binaries/${{ github.sha }}/

      - name: Upload latest metadata
        run: aws s3 cp python/dist/server/latest.txt s3://truffle-binaries/latest.txt