name: Release server executable

on:
  pull_request:
    branches:
      - release
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      DATABASE_URL: "sqlite+aiosqlite:///${{ github.workspace }}/truffle.test.db"
    strategy:
      fail-fast: false
      matrix:
        os: [
            macos-latest, 
            ubuntu-cuda12.1-x86_64-1x-4090,
        ]
        include:
          - os: macos-latest
            filename: darwin-metal-arm64.zip
          - os: ubuntu-cuda12.1-x86_64-1x-4090
            filename: linux-cuda-x64.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: truffle
          python-version: "3.10"
          channels: conda-forge,spyder-ide

      - run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate truffle

      - name: Install dependencies
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate truffle
          pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly
          elif [ "${{ matrix.os }}" == "ubuntu-cuda12.1-x86_64-1x-4090" ]; then
            pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu121 mlc-ai-nightly-cu121
          fi
          pip install -r python/requirements.txt

      - name: Apply the patch
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate truffle
          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
          patch -d $SITE_PACKAGES/mlc_llm -p1 < truffle.patch --verbose
          if [ "${{ matrix.os }}" == "ubuntu-cuda12.1-x86_64-1x-4090" ]; then
            sed -i '/cmd = \["nvcc"\]/c\    cuda_path = find_cuda_path(); print("---- CUDA PATH:", cuda_path); cmd = [os.path.join(cuda_path, "bin", "nvcc")]' $SITE_PACKAGES/tvm/contrib/nvcc.py
          fi

      - name: Import certificate to keychain
        if: matrix.os == 'macos-latest'
        run: |
          echo "${{ secrets.APPLE_CODESIGN_CERT }}" | base64 --decode > certificate.p12
          security create-keychain -p temporary build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p temporary build.keychain
          security import certificate.p12 -k build.keychain -P runescape -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k temporary build.keychain
          security list-keychains -d user -s build.keychain
          security find-identity -v -p codesigning

      - name: Build server executable
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate truffle
          cd python
          pyinstaller server.spec --clean --noconfirm --log-level=DEBUG

      # - name: Disable local cuda for integration tests
      #   run: |
      #     if [ "${{ matrix.os }}" == "ubuntu-cuda12.1-1xt4-x86_64" ]; then
      #       export PATH=$(echo $PATH | sed -e 's/:\/usr\/local\/cuda[^:]*//g')
      #       export LD_LIBRARY_PATH=$(echo $LD_LIBRARYPATH | sed -e 's/:\/usr\/local\/cuda[^:]*//g')
      #       if nvcc -V; then
      #         echo "** CUDA compiler is still accessible, failing the test. **"
      #         exit 1
      #       else
      #         echo "** CUDA compiler not accessible, as expected. **"
      #       fi
      #     fi

      - name: Copy extra files
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate truffle
          cp -r python/alembic python/dist/server/alembic
          echo ${{ github.sha }} > python/dist/server/version.txt
          if [ "${{ matrix.os }}" == "ubuntu-cuda12.1-x86_64-1x-4090" ]; then
            cp -rL /usr/local/cuda python/dist/server/_internal/cuda
          fi

      - name: Run integration tests
        if: matrix.os == 'macos-latest'
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate truffle
          cd python/dist/server 
          nohup ./server &
          sleep 5
          curl --retry 5 --retry-connrefused http://localhost:8899
          cd ../../
          PYTHONPATH="." pytest --maxfail=1 -vvv tests/integration

      - name: Archive server executable
        run: |
          cd python/dist
          zip -ry ${{ matrix.filename }} server

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp python/dist/${{ matrix.filename }} s3://truffle-binaries/${{ github.sha }}/

      - name: Upload latest metadata
        run: aws s3 cp python/dist/server/version.txt s3://truffle-binaries/latest.txt

      - name: Notarize the binary from apple
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            xcrun notarytool submit python/dist/${{ matrix.filename }} --apple-id accounts@deepshard.org --password rhbl-cubs-tult-hrwy --team-id 4SDV2299VV
          fi

      - name: Cleanup
        run: killall server || true

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Server executable release ${{ job.status == 'success' && 'succeeded! :rocket:' || 'failed! :x:' }}
            New Version: `${{ github.sha }}` | `${{ matrix.os }}`
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}
