name: Release frontend app

on:
  push:
  pull_request:
    branches:
      - release
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Install Bun
        run: npm install -g bun

      - name: Install dependencies
        run: bun install

      - name: Import certificate to keychain
        run: |
          echo "${{ secrets.APPLE_CODESIGN_CERT }}" | base64 --decode > certificate.p12
          security create-keychain -p temporary build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p temporary build.keychain
          security import certificate.p12 -k build.keychain -P runescape -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k temporary build.keychain
          security list-keychains -d user -s build.keychain
          security find-identity -v -p codesigning

      - run: NODE_ENV=production AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} ./publish.sh

      - name: Notify Slack on success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Frontend app release succeeded! :rocket:'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Frontend app release failed! :x:'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}

